image: ruby:2.6

cache:
  paths:
  - vendor/

before_script:
  - cd docs
  - bundle install --path vendor

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - docs/public
  only:
  - master

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - docs/test
  except:
  - master