image: ruby:2.3

variables:
  JEKYLL_ENV: production

pages:
  script:
  - cd docs
  - bundle exec jekyll build -d public
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
